[MODEL_CONFIG]
rmsp_alpha = 0.99 
rmsp_epsilon = 1e-5 
; max_grad_norm = 40
; max_grad_norm = 1
; lr_init = 5e-4
; lr_init = 1e-4
entropy_coef = 0.05 
; entropy_coef = 0.1
batch_size = 60
; gamma = 0.99
gamma = 0.9
lr_decay = constant
value_coef = 0.5 
num_lstm = 64
num_fc = 64
reward_norm = 800.0
reward_clip = -1 
; v1
; max_grad_norm = 1
; lr = 0.0005
; v2
; max_grad_norm = 10
; lr = 0.0005
; v2
; max_grad_norm = 40
; lr = 0.0005
; v3
max_grad_norm = 10
lr = 0.001

slow_lr = 0.002
fast_lr = 0.01
eps = 0.05
max_ep_len = 20
; n_episodes = 20000
n_episodes = 1000000
n_ep_fixed = 32
n_epochs = 20
; lr = 0.0005

[TRAIN_CONFIG]
; total_step = 20000
; log_interval = 500
; test_interval = 2000
total_step = 1e6
test_interval = 2e6
log_interval = 1e3

[ENV_CONFIG]
scenario = grid_world
agent = d2ac
; seed = 0
seed = 42
; seed = 123
nrow = 10
ncol = 10
n_agent = 5
n_states = 2
n_actions = 5
randomize_state = False
initial_state = [[0,0],[0,1],[1,2],[1,3],[2,4]]
desired_state = [[4,4],[4,3],[4,2],[2,3],[1,3]]
in_nodes = [[0,1,2,3],[1,2,3,4],[2,3,4,0],[3,4,0,1],[4,0,1,2]]
use_gpu = True
coop_gamma = -1
use_distributional = 1