[MODEL_CONFIG]
rmsp_alpha = 0.99 
rmsp_epsilon = 1e-5 
; max_grad_norm = 40
; lr_init = 5e-4
entropy_coef = 0.05 
; entropy_coef = 0.1
batch_size = 60
gamma = 0.99
lr_decay = constant
value_coef = 0.5 
num_lstm = 64
num_fc = 64
; same nodes may be updated by ~8 propagations,
; adjust norm accordingly
reward_norm = 5000.0
reward_clip = -1
; v2
; lr_init = 1e-4
; max_grad_norm = 1
; v3
; lr_init = 1e-4
; max_grad_norm = 10
; v4
; lr_init = 5e-4
; max_grad_norm = 10
; v5
lr_init = 1e-4
max_grad_norm = 40

[TRAIN_CONFIG]
; total_step = 20000
; log_interval = 500
; test_interval = 2000
total_step = 1e6
test_interval = 2e6
log_interval = 1e3

[ENV_CONFIG]
scenario = grid_world
agent = ma2c_cnet
seed = 0
nrow = 10
ncol = 10
n_agent = 5
randomize_state = False
initial_state = [[0,0],[0,1],[1,2],[1,3],[2,4]]
desired_state = [[4,4],[4,3],[4,2],[2,3],[1,3]]
use_gpu = True
coop_gamma = -1