[MODEL_CONFIG]
rmsp_alpha = 0.99 
rmsp_epsilon = 1e-5 
; max_grad_norm = 10
; max_grad_norm = 1
gamma = 0.99
; lr_init = 5e-4
; lr_init = 1e-4
lr_decay = constant
entropy_coef = 0.05 
value_coef = 0.5 
num_lstm = 64
num_fc = 64
batch_size = 60
reward_norm = 800.0
reward_clip = -1 
; v5
; max_grad_norm = 40
; lr_init = 5e-4
; v6
; max_grad_norm = 10
; lr_init = 1e-4
; v7
max_grad_norm = 10
lr_init = 1e-4

[TRAIN_CONFIG]
total_step = 1e6
test_interval = 2e6
log_interval = 1e3

[ENV_CONFIG]
scenario = grid_world
agent = d2ac_cu
seed = 0
nrow = 10
ncol = 10
n_agent = 5
randomize_state = False
initial_state = [[0,0],[0,1],[1,2],[1,3],[2,4]]
desired_state = [[4,4],[4,3],[4,2],[2,3],[1,3]]
use_gpu = True
coop_gamma = -1