[MODEL_CONFIG]
rmsp_alpha = 0.99 
rmsp_epsilon = 1e-5 
; max_grad_norm = 40
max_grad_norm = 1
; lr_init = 5e-4
; lr_init = 1e-4
entropy_coef = 0.05 
; entropy_coef = 0.1
batch_size = 60
gamma = 0.99
lr_decay = constant
value_coef = 0.5 
num_lstm = 64
num_fc = 64
reward_norm = 800.0
reward_clip = -1 

slow_lr = 0.002
fast_lr = 0.01
eps = 0.05
; n_episodes = 20000
n_episodes = 1000000
n_ep_fixed = 32
n_epochs = 20
max_ep_len = 20
; n_epochs = 5
; max_ep_len = 200

lr = 0.0005

# 训练参数
; n_episodes = 15000
; n_ep_fixed = 10
; max_ep_len = 300
; n_epochs = 3
; gamma = 0.99
; eps = 0.3
; slow_lr = 1e-4
; fast_lr = 3e-4


[TRAIN_CONFIG]
; total_step = 20000
; log_interval = 500
; test_interval = 2000
total_step = 1e6
test_interval = 2e6
log_interval = 1e3

[ENV_CONFIG]
scenario = cacc_catchup
control_interval_sec = 0.1
episode_length_sec = 60
agent = d2ac
batch_size = 60
; coop_gamma = -1
coop_gamma = 0.9
; constraints
headway_min = 1
headway_st = 5
headway_go = 35
speed_max = 30
accel_max = 2.5
accel_min = -2.5 
; reward 
reward_v = 1
reward_u = 0.1
; reward_v = 0.05
; reward_u = 0.01
; collision_penalty = 1000
collision_penalty = 500
headway_target = 20
speed_target = 15
norm_headway = 10
norm_speed = 7.5
n_vehicle = 6
seed = 12
test_seeds = 10000
yellow_interval_sec = 2
use_gpu = True

; # distributional参数
use_distributional = 1
; # 这个会被动态计算覆盖
n_states = 40  
; in_nodes = [[0,1],[0,1,2],[1,2,3],[2,3,4],[3,4,5],[4,5,6],[5,6,7],[6,7]]
in_nodes = [[0,1],[0,1,2],[1,2,3],[2,3,4],[3,4,5],[4,5]]
; seed = 0
; nrow = 10
; ncol = 10
; n_agent = 5
; n_states = 2
; n_actions = 5
; randomize_state = False
; initial_state = [[0,0],[0,1],[1,2],[1,3],[2,4]]
; desired_state = [[4,4],[4,3],[4,2],[2,3],[1,3]]
; in_nodes = [[0,1,2,3],[1,2,3,4],[2,3,4,0],[3,4,0,1],[4,0,1,2]]
; use_gpu = True
; coop_gamma = -1
; use_distributional = 1